// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZbgU2Le0eEdmbAhlj5TBnpgxsdMgAW2U',
    appId: '1:244053305794:android:60004763fd2e38cf888e5b',
    messagingSenderId: '244053305794',
    projectId: 'ulima-plus-chat',
    databaseURL: 'https://ulima-plus-chat-default-rtdb.firebaseio.com',
    storageBucket: 'ulima-plus-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrGnStsck0l6zcPS2FRr8QyAOOmyRKuIw',
    appId: '1:244053305794:ios:d0fce8bbd0097ac9888e5b',
    messagingSenderId: '244053305794',
    projectId: 'ulima-plus-chat',
    databaseURL: 'https://ulima-plus-chat-default-rtdb.firebaseio.com',
    storageBucket: 'ulima-plus-chat.firebasestorage.app',
    iosBundleId: 'com.grupo5.ulimaplus',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZbgU2Le0eEdmbAhlj5TBnpgxsdMgAW2U',
    appId: '1:244053305794:web:0000000000000000000000',
    messagingSenderId: '244053305794',
    projectId: 'ulima-plus-chat',
    databaseURL: 'https://ulima-plus-chat-default-rtdb.firebaseio.com',
    storageBucket: 'ulima-plus-chat.firebasestorage.app',
  );
}
