name: Build and Release APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Instalar Flutter
        run: |
          git clone https://github.com/flutter/flutter.git --depth 1 -b stable "$HOME/flutter"
          echo "$HOME/flutter/bin" >> "$GITHUB_PATH"

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Instalar dependencias
        run: flutter pub get

      - name: Compilar APK
        run: flutter build apk --release

      - name: Preparar APK
        run: |
          mkdir -p release
          cp build/app/outputs/flutter-apk/app-release.apk release/ULimaPlus.apk

      - name: Crear o actualizar Release latest
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: ULima++ Latest
          body: APK generado automáticamente desde la rama main.
          files: release/ULimaPlus.apk
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}